# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 22:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=200)),
                ('book_edition', models.IntegerField(default=1)),
                ('book_theme', models.CharField(max_length=30)),
                ('publishing_year', models.IntegerField()),
                ('registered_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('authors', models.ManyToManyField(to='mylib.Author')),
            ],
            options={
                'ordering': ('registered_date',),
            },
        ),
        migrations.CreateModel(
            name='PublishingPress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publishing_press', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='publishing_presses',
            field=models.ManyToManyField(to='mylib.PublishingPress'),
        ),
    ]
